### ISSUE TITLE
3D-map positioning

### ISSUE THREAD

**Issue by landswellsong** [IonosatMicro/promis-frontend#20]
When swtiching from 2D to 3D, the map refocuses to a seemingly random spot. This probably isn't desirable.

**Comment by lyssdod** [comment]
It's the same spot, just with scrolling animation and/or possibly another zoom level.

**Comment by landswellsong** [comment]
Nope, changes places every time I switch maps in my setup :(

**Comment by landswellsong** [comment]
Ok my bad, but it's still a bug. When you switch to 2D, move around and then switch to 3D, the globe opens up at the last 3D position and does the animation of rotation to the 2D point. This is confusing and shouldn't work that way I think.
